# Generated by Django 4.0.4 on 2022-05-26 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_remove_collections_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionsimage',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
