# Generated by Django 4.0.4 on 2022-05-26 06:04

import ckeditor.fields
import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_alter_collectionsimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('article', models.CharField(max_length=150)),
                ('price', models.IntegerField(null=True)),
                ('old_price', models.IntegerField(null=True)),
                ('sales', models.IntegerField(null=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('size_range', models.CharField(max_length=150)),
                ('compound', models.CharField(max_length=150)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('material', models.CharField(max_length=150)),
                ('hit', models.BooleanField(default=False)),
                ('new', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products_photo')),
                ('color', colorfield.fields.ColorField(default='#FFFFFFFF', image_field=None, max_length=18, samples=None)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='collection.product')),
            ],
        ),
    ]
