# Generated by Django 4.0.4 on 2022-05-26 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_product_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
