# Generated by Django 4.0.4 on 2022-05-26 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0005_offer_alter_about_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutimage',
            old_name='about_us',
            new_name='about',
        ),
    ]
