# Generated by Django 4.0.4 on 2022-05-26 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0006_rename_about_us_aboutimage_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advantagesimage',
            name='advantages',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advantages', to='about_us.advantages'),
        ),
    ]
