# Generated by Django 4.0.4 on 2022-05-27 07:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0007_alter_advantagesimage_advantages'),
    ]

    operations = [
        migrations.AddField(
            model_name='help',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='HelpImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('help', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help', to='about_us.help')),
            ],
        ),
    ]
