# Generated by Django 4.0.4 on 2022-05-27 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0008_help_image_helpimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutimage',
            name='about',
        ),
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='AboutImage',
        ),
    ]
