# Generated by Django 4.0.4 on 2022-05-26 10:14

import ckeditor.fields
import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collection', '0006_remove_productimage_product_delete_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('color', colorfield.fields.ColorField(default='#FFFFFFFF', image_field=None, max_length=18, samples=None)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('article', models.CharField(max_length=150)),
                ('price', models.IntegerField(null=True)),
                ('old_price', models.IntegerField(null=True)),
                ('sales', models.IntegerField(null=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('size_range', models.CharField(max_length=150)),
                ('compound', models.CharField(max_length=150)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('material', models.CharField(max_length=150)),
                ('hit', models.BooleanField(default=False)),
                ('new', models.BooleanField(default=False)),
                ('collections', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='collection.collections')),
            ],
        ),
    ]
