# Generated by Django 4.0.4 on 2022-05-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_rename_old_price_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_sales',
            field=models.IntegerField(null=True),
        ),
    ]
