# Generated by Django 4.0.4 on 2022-05-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_price_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_sales',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
